<?php
    echo $this->headtitle($this->escapehtml($this->translate('Cài đặt')));
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h3 class="page-title">
                Cài đặt <small>Tùy chọn trang chủ</small>
            </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home" aria-hidden="true"></i>
                    <a>Admin</a>
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                    <a>Tùy chọn</a>

                </li>
            </ul>
        </div>
    </div>

<div class="row-fluid">
    <div class="span12">
        <table id="user" class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <td style="width:15%">Tiêu đề trang</td>
                    <td style="width:50%"><a href="#" id="titlePage" data-type="text" data-pk="1" data-original-title="Tiêu đề trang"></a></td>
                    <td style="width:35%"><span class="muted">Tiêu đề trang chủ</span></td>
                </tr>
                <tr>
                    <td style="width:15%">Logo</td>
                    <td style="width:50%"><a href="#" id="Logo" data-type="text" data-pk="1" data-original-title="Logo"></a></td>
                    <td style="width:35%"><span class="muted">Url Logo</span></td>
                </tr>
                <tr>
                    <td style="width:15%">Favicon</td>
                    <td style="width:50%"><a href="#" id="Favicon" data-type="text" data-pk="1" data-original-title="Favicon"></a></td>
                    <td style="width:35%"><span class="muted">Url Favicon</span></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>

<script>
    $(document).ready(function(){
        $('#titlePage').editable({
            url: '/admin/setup'
        });
        $('#Logo').editable({
            url: '/admin/setup'
        });
        $('#Favicon').editable();

    });
</script>