<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách Menu')));
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h3 class="page-title">
                Danh sách Menu
            </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/admin">Admin</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="/admin/setup/menu">Menu</a>
                </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-edit"></i>Danh sách Menu</div>
                </div>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a href="/admin/setup/addmenu" id="sample_editable_1_new" class="btn green">
                                Thêm mới <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Công cụ <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Print</a></li>
                                <li><a href="#">Save as PDF</a></li>
                                <li><a href="#">Export to Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row-fluid" style="display: none">
                            <div class="span2"></div>
                            <div class="span10">
                                <?php
                                echo $this->partial ( 'partial/form', array (
                                    'form' => $this->fFilter
                                ));
                                ?>
                            </div>
                        </div>
                        <div class="dg-container">
                            <div class="span6">
                                <table class="dg table table-bordered table-hover table-condensed">
                                    <thead>
                                        <tr>
                                            <th colspan="3">Menu chính</th>
                                        </tr>
                                        <tr>
                                            <th>Tên</th>
                                            <th style="text-align: center;width: 12%">Thứ tự</th>
                                            <th style="text-align: center;width: 16%">Trạng thái</th>
                                            <th style="text-align: center;width: 10%">Xóa</th>
                                        </tr>
                                    </thead>
                                    <?php
                                        if(count($this->results)){
                                    ?>
                                    <tbody>
                                        <?php
                                            foreach($this->results as $m){
                                                if($m->getPositionId() == 1){
                                        ?>
                                        <tr>
                                            <td><a href="/admin/setup/editmenu/<?= $m->getId() ?>"><?= $m->getName() ?></a></td>
                                            <td class="align-center"><a style="cursor: pointer;" class="updateOrder" title="Lên đầu" data-id="<?= $m->getId() ?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></td>
                                            <td class="align-center"><a class="statusChange" data-id="<?= $m->getId() ?>"><?= $m->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                            <td class="align-center"><a data-id="<?= $m->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                        </tr>
                                        <?php
                                            if($m->getChilds()){
                                                foreach($m->getChilds() as $mm){
                                                    ?>
                                                    <tr>
                                                        <td><a href="/admin/setup/editmenu/<?= $mm->getId() ?>"> ----- <?= $mm->getName() ?></a></td>
                                                        <td class="align-center"><a style="cursor: pointer;" class="updateOrder" title="Lên đầu" data-id="<?= $mm->getId() ?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></td>
                                                        <td class="align-center"><a class="statusChange" data-id="<?= $mm->getId() ?>"><?= $mm->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                                        <td class="align-center"><a data-id="<?= $mm->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                                    </tr>
                                                    <?php
                                                    if($mm->getChilds()){
                                                        foreach($mm->getChilds() as $mmm){
                                                            ?>
                                                            <tr>
                                                                <td><a href="/admin/setup/editmenu/<?= $mmm->getId() ?>"> ---------- <?= $mmm->getName() ?></a></td>
                                                                <td class="align-center"><a style="cursor: pointer;" class="updateOrder" title="Lên đầu" data-id="<?= $mmm->getId() ?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></td>
                                                                <td class="align-center"><a class="statusChange" data-id="<?= $mmm->getId() ?>"><?= $mmm->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                                                <td class="align-center"><a data-id="<?= $mmm->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                                            </tr>
                                                            <?php
                                                            if($mmm->getChilds()){
                                                                foreach($mmm->getChilds() as $mmmm){
                                                                    ?>
                                                                    <tr>
                                                                        <td><a href="/admin/setup/editmenu/<?= $mmmm->getId() ?>"> ---------- <?= $mmmm->getName() ?></a></td>
                                                                        <td class="align-center"><a style="cursor: pointer;" class="updateOrder" title="Lên đầu" data-id="<?= $mmmm->getId() ?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></td>
                                                                        <td class="align-center"><a class="statusChange" data-id="<?= $mmmm->getId() ?>"><?= $mmmm->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                                                        <td class="align-center"><a data-id="<?= $mmmm->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                                                    </tr>
                                                                <?php
                                                                }
                                                            }
                                                            ?>
                                                        <?php
                                                        }
                                                    }
                                                    ?>
                                                <?php
                                                }
                                            }
                                        ?>
                                        <?php } }?>
                                    </tbody>
                                    <?php
                                        }
                                    ?>
                                </table>
                            </div>
                            <div class="span6">
                                <table class="dg table table-bordered table-hover table-condensed">
                                    <thead>
                                    <tr>
                                        <th colspan="3">Menu Footer</th>
                                    </tr>
                                    <tr>
                                        <th>Tên</th>
                                        <th style="text-align: center;width: 16%">Trạng thái</th>
                                        <th style="text-align: center;width: 10%">Xóa</th>
                                    </tr>
                                    </thead>
                                    <?php
                                    if(count($this->results)){
                                        ?>
                                        <tbody>
                                        <?php
                                        foreach($this->results as $m){
                                            if($m->getPositionId() == 2){
                                                ?>
                                                <tr>
                                                    <td><a href="/admin/setup/editmenu/<?= $m->getId() ?>"><?= $m->getName() ?></a></td>
                                                    <td class="align-center"><a class="statusChange" data-id="<?= $m->getId() ?>"><?= $m->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                                    <td class="align-center"><a data-id="<?= $m->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                                </tr>
                                                <?php
                                                if($m->getChilds()){
                                                    foreach($m->getChilds() as $mm){
                                                        ?>
                                                        <tr>
                                                            <td><a href="/admin/setup/editmenu/<?= $mm->getId() ?>"> ----- <?= $mm->getName() ?></a></td>
                                                            <td class="align-center"><a class="statusChange" data-id="<?= $mm->getId() ?>"><?= $mm->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                                            <td class="align-center"><a data-id="<?= $mm->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                                        </tr>
                                                        <?php
                                                        if($mm->getChilds()){
                                                            foreach($mm->getChilds() as $mmm){
                                                                ?>
                                                                <tr>
                                                                    <td><a href="/admin/setup/editmenu/<?= $mmm->getId() ?>"> ---------- <?= $mmm->getName() ?></a></td>
                                                                    <td class="align-center"><a class="statusChange" data-id="<?= $mmm->getId() ?>"><?= $mmm->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                                                    <td class="align-center"><a data-id="<?= $mmm->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                                                </tr>
                                                                <?php
                                                                if($mmm->getChilds()){
                                                                    foreach($mmm->getChilds() as $mmmm){
                                                                        ?>
                                                                        <tr>
                                                                            <td><a href="/admin/setup/editmenu/<?= $mmmm->getId() ?>"> ---------- <?= $mmmm->getName() ?></a></td>
                                                                            <td class="align-center"><a class="statusChange" data-id="<?= $mmmm->getId() ?>"><?= $mmmm->getStatus() == 1 ? '<i class="fa fa-eye"></i>':'<i class="fa fa-eye-slash"></i>' ?></a></td>
                                                                            <td class="align-center"><a data-id="<?= $mmmm->getId() ?>" class="deleteMenu fa fa-trash-o"></a></td>
                                                                        </tr>
                                                                    <?php
                                                                    }
                                                                }
                                                                ?>
                                                            <?php
                                                            }
                                                        }
                                                        ?>
                                                    <?php
                                                    }
                                                }
                                                ?>
                                            <?php } }?>
                                        </tbody>
                                    <?php
                                    }
                                    ?>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

</div>

<div id="confdelete"></div>
<div id="err"></div>
<div id="uploadimg"></div>
<style>
    .align-center{
        text-align: center !important;
    }
    .dg-container{
        display: inline-block;
        width: 100%;
    }
    .fFilter{
        text-align: right;
    }
    .fFilter #id{
        width: 10% !important;
        margin: 0 5px 0 0;
    }
    .fFilter #name{
        margin: 0 5px 0 0;
    }
    table a{
        cursor: pointer;
    }
</style>

<script>
    $(function(){

        var hide = true;
        var t = $('.deleteMenu');
        var clicks = true;

        t.click(function() {
            var t = $(this);
            var td = t.closest('tr');
            if (clicks) {
                $(this).text('OK');
                $(this).removeClass('fa fa-trash-o');
                clicks = false;
            } else {
                $.post('/admin/setup/deletemenu',{
                    id: $(this).attr('data-id')
                },function(r){
                    if(r.code == 0){
                        alert(r.messenger);
                    }else if(r.code == 1){
                        td.fadeOut(600,function(){
                            td.remove();
                        });
                    }
                });
                clicks = true;
            }
        });

        $('html').click(function(e){
            if ($(e.target).hasClass('deleteMenu')) {
                return false;
            }
            if(hide){
                t.addClass('fa fa-trash-o').text('');
            }
            clicks = true;
            hide = true;
        });


        $('.statusChange').click(function(){
            var id = $(this).attr('data-id'), _this = $(this);

            $.post('/admin/setup/changeStatus',{id: id},function(r){
                if(r.code == 1){
                    if(r.status == 1){
                        _this.find('i').remove();
                        _this.append('<i class="fa fa-eye"></i>');
                    }else if(r.status == 0){
                        _this.find('i').remove();
                        _this.append('<i class="fa fa-eye-slash"></i>');
                    }
                }else if(r.code == 0){
                    alert(r.messenger);
                }
            });
        });

        $('.updateOrder').click(function(){
            var id = $(this).attr('data-id'), _this = $(this);

            $.post('/admin/setup/changeStatus',{id: id, order: true},function(r){
                if(r.code == 1){
                    location.reload();
                }else if(r.code == 0){
                    alert(r.messenger);
                }
            });
        });


    });
</script>
