<?php
echo $this->headtitle($this->escapehtml($this->translate('Thêm')));

?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
    <form method="post" enctype="multipart/form-data">
        <div class="row-fluid">
            <div class="span8">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="fa fa-navicon"></i>Thêm</div>
                    </div>
                    <div class="portlet-body form">
                        <?php
                        $form = $this->form;
                        ?>
                        <div class="row-fluid">
                            <div class="span9">
                                <div class="control-group">
                                    <label class="control-label" for="firstName">Tên</label>
                                    <div class="controls">
                                        <?=$this->formelement($form->get('name')->setAttributes(['class' => 'm-wrap span12','placeholder'=>'Tiêu đề']))?>
                                        <?= $this->formelementerrors($form->get('name'),['class' => 'help-block'])?>
                                    </div>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="control-group">
                                    <label class="control-label" for="firstName">Danh mục cha</label>
                                    <div class="controls">
                                        <?=$this->formelement($form->get('parentId')->setAttributes(['class' => 'm-wrap span12', 'id' => 'textarea_full1','placeholder'=>'Nội dung']))?>
                                        <?= $this->formelementerrors($form->get('parentId'),['class' => 'help-block'])?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label" for="firstName">Mô tả</label>
                                    <div class="controls">
                                        <?=$this->formelement($form->get('description')->setAttributes(['class' => 'm-wrap span12', 'id' => 'textarea_full','placeholder'=>'Nội dung']))?>
                                        <?= $this->formelementerrors($form->get('description'),['class' => 'help-block'])?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn blue']))?>
                            <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="span4">
                <div class="portlet box grey">
                    <div class="portlet-title">
                        <div class="caption"><i class="fa fa-navicon"></i>Tùy chọn</div>
                    </div>
                    <div class="portlet-body form">
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="control-group">
                                    <label class="control-label" for="firstName">Trạng thái</label>
                                    <div class="controls">
                                        <?=$this->formelement($form->get('status')->setAttributes(['class' => 'm-wrap span12', 'id' => 'textarea_full','placeholder'=>'Nội dung']))?>
                                        <?= $this->formelementerrors($form->get('status'),['class' => 'help-block'])?>
                                    </div>
                                </div>
                            </div>

                            <div class="span6">
                                <div class="control-group">
                                    <label class="control-label" for="firstName">Gian hàng</label>
                                    <div class="controls">
                                        <?=$this->formelement($form->get('storeId')->setAttributes(['class' => 'm-wrap span12', 'id' => 'storeId']))?>
                                        <?= $this->formelementerrors($form->get('storeId'),['class' => 'help-block'])?>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </form>
</div>
<style>
    .portlet-tabs .nav-tabs{
        height: 41px;
    }
    .nav-tabs li a{
        color: #FFF;
    }
    .nav-tabs li a:hover{
        color: #333;
    }
    #image_upload{
        border: none;
        overflow: hidden;
    }
    #image_upload:focus{
        outline: none;
    }
    #image_upload:before{
        content: 'Chọn File ảnh';
        display: inline-block;
        background: #FFF;
        border: 1px solid #CCC;
        padding: 1px 0;
        width: 99%;
        outline: none;
        white-space: nowrap;
        -webkit-user-select: none;
        cursor: pointer;
        text-shadow: 1px 1px #fff;
        font-size: 10pt;
        text-indent: 10px;
    }
</style>
<?php
?>
