<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách Danh mục')));
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h3 class="page-title">
                Danh sách Danh mục
            </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/admin">Admin</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="/admin/article/category">Danh mục</a>
                </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-edit"></i>Danh sách Danh mục</div>
                </div>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a href="/admin/article/addcategory" id="sample_editable_1_new" class="btn green">
                                Thêm mới <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Công cụ <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Print</a></li>
                                <li><a href="#">Save as PDF</a></li>
                                <li><a href="#">Export to Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row-fluid">
                            <div class="span3"></div>
                            <div class="span9">
                                <?php
                                echo $this->partial ( 'partial/form', array (
                                    'form' => $this->fFilter
                                ));
                                ?>
                            </div>
                        </div>
                        <?php
                        echo $dg = new \Admin\Dg\DgArticlec( array (
                            'data' => $this->results->getData (),
                            'paging' => $this->results->getPaging (),
                            'rowCount' => $this->results->getRowCount (),
                            'rowInPage' => $this->results->getRowInPage (),
                        ));
                        ?>
                    </div>

                </div>

            </div>
        </div>
    </div>

</div>

<div id="confdelete"></div>
<div id="err"></div>
<div id="uploadimg"></div>
<style>
    .dg-container{
        display: inline-block;
        width: 100%;
    }
    .fFilter{
        text-align: right;
    }
    .fFilter #id{
        width: 10% !important;
        margin: 0 5px 0 0;
    }
    .fFilter #name{
        margin: 0 5px 0 0;
    }
</style>
<script>
    $(function(){
        $('.changeType').click(function(){
            var id = $(this).attr('data-id'), _this = $(this);

            $.post('/admin/article/changec',{id: id},function(r){
                if(r.code == 1){
                    if(r.status == 1){
                        _this.find('i').remove();
                        _this.append('<i class="fa fa-eye"></i>');
                    }else if(r.status == 0){
                        _this.find('i').remove();
                        _this.append('<i class="fa fa-eye-slash"></i>');
                    }
                }else if(r.code == 0){
                    alert(r.messenger);
                }
            });
        });
    });
</script>