<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Base\Module'                                    => __DIR__ . '/Module.php',
    'Base\Db\Adapter\MasterSlaveAdapter'             => __DIR__ . '/src/Base/Db/Adapter/MasterSlaveAdapter.php',
    'Base\Db\Adapter\MasterSlaveAdapterInterface'    => __DIR__ . '/src/Base/Db/Adapter/MasterSlaveAdapterInterface.php',

    'Base\EventManager\EventProvider'                => __DIR__ . '/src/Base/EventManager/EventProvider.php',

    'Base\Form\ProvidesEventsForm'                   => __DIR__ . '/src/Base/Form/ProvidesEventsForm.php',
	'Base\Form\OptionalSelect'                       => __DIR__ . '/src/Base/Form/OptionalSelect.php',

    'Base\InputFilter\ProvidesEventsInputFilter'     => __DIR__ . '/src/Base/InputFilter/ProvidesEventsInputFilter.php',
	'Base\Filter\HTMLPurifier'     			 		=> __DIR__ . '/src/Base/Filter/HTMLPurifier.php',

    'Base\Mapper\AbstractDbMapper'                   => __DIR__ . '/src/Base/Mapper/AbstractDbMapper.php',
    'Base\Mapper\Base'                               => __DIR__ . '/src/Base/Mapper/Base.php',
    'Base\Mapper\Exception\ExceptionInterface'       => __DIR__ . '/src/Base/Mapper/Exception/ExceptionInterface.php',
    'Base\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/Base/Mapper/Exception/InvalidArgumentException.php',

    'Base\Model\Base'                                => __DIR__ . '/src/Base/Model/Base.php',
    'Base\Model\Resource'                            => __DIR__ . '/src/Base/Model/Resource.php',
    'Base\Model\Uri'                                 => __DIR__ . '/src/Base/Model/Uri.php',
    'Base\Model\RDate'                               => __DIR__ . '/src/Base/Model/RDate.php',
    'Base\Model\Format'                              => __DIR__ . '/src/Base/Model/Format.php',
    'Base\Model\Ultility'                            => __DIR__ . '/src/Base/Model/Ultility.php',

    'Base\Module\AbstractModule'                     => __DIR__ . '/src/Base/Module/AbstractModule.php',

    'Base\View\Helper\UriParams'                     => __DIR__ . '/src/Base/View/Helper/UriParams.php',
);
