<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authorize\Module'                             => __DIR__ . '/Module.php',
    'Authorize\Controller\Plugin\IsAllowed'        => __DIR__ . '/src/Authorize/Controller/Plugin/IsAllowed.php',
    'Authorize\Guard\Controller'                   => __DIR__ . '/src/Authorize/Guard/Controller.php',
    'Authorize\Permission\Acl'                     => __DIR__ . '/src/Authorize/Permission/Acl.php',
    'Authorize\Service\Authorize'                  => __DIR__ . '/src/Authorize/Service/Authorize.php',
    'Authorize\View\Strategy\UnauthorizedStrategy' => __DIR__ . '/src/Authorize/View/Strategy/UnauthorizedStrategy.php',
);
