<?php
    $f = $this->results->getData();
    if(isset($f)){
        foreach($f as $ff){
            echo '<li data-id="'.$ff->getId().'"><img src="'.$ff->getPictureUri().'" alt=""/></li>';
        }
    }
?>
<style>
    ul.listImage li{
        list-style: none;
        width: 24%;
        margin: 0 1% 5px 0;
        display: inline-block;
        position: relative;
        height: 80px;
        overflow: hidden;
        background: #f9f9f9;
    }
    ul.listImage li.active:before{
        content: 'Đã chọn';
        width: 100%;
        height: 100%;
        display: block;
        background: rgba(60, 60, 60, 0.52);
        opacity: 1;
        top: 0;
        line-height: 80px;
        color: #FFF;
        left: 0;
        z-index: 1;
        position: absolute;
        text-align: center;
    }
    ul.listImage li img{
        max-width: 100%;
        position: absolute;
        top: 0;
        bottom: 0;
        margin: auto;
    }
    ul.listImage{
        padding: 0 0;
        margin: 0 0;
    }
</style>