<script>
$(function(){
	$('.brand').click(function(){
		$('#slide-left').toggle();
		$('#slide-left').css({'opacity':'1'});
	});
 });
</script>
<div id="slide-left">
	<ul>
		<li><a href="#"><i class="fa fa-sign-out"></i>Thêm sản phẩm</a></li>
		<li><a href="#"><i class="fa fa-sign-out"></i>Thêm danh mục sản phẩm</a></li>
		<li><a href="#"><i class="fa fa-sign-out"></i>Thêm bài viết</a></li>
		<li><a href="#"><i class="fa fa-sign-out"></i>Thêm danh mục bài viết</a></li>
		<li><a href="#"><i class="fa fa-sign-out"></i>Thêm người dùng</a></li>
		
	</ul>
</div>