<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'News\Module'                          => __DIR__ . '/Module.php',
    'News\Controller\NewsController'       => __DIR__ . '/src/News/Controller/NewsController.php',
    'News\Model\Article'                   => __DIR__ . '/src/News/Model/Article.php',
    'News\Model\ArticleMapper'             => __DIR__ . '/src/News/Model/ArticleMapper.php',
    'News\Model\Category'                  => __DIR__ . '/src/News/Model/Category.php',
    'News\Model\CategoryMapper'            => __DIR__ . '/src/News/Model/CategoryMapper.php',
    'News\Service\News'                    => __DIR__ . '/src/News/Service/News.php',
    'News\View\Helper\News'                => __DIR__ . '/src/News/View/Helper/News.php',
    'News\View\Helper\NewsCategory'        => __DIR__ . '/src/News/View/Helper/NewsCategory.php',
    'News\View\Helper\NewsCategoryFactory' => __DIR__ . '/src/News/View/Helper/NewsCategoryFactory.php',
    'News\View\Helper\NewsFactory'         => __DIR__ . '/src/News/View/Helper/NewsFactory.php',
);
