<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Uitemplate\Module'                 => __DIR__ . '/Module.php',
  'Uitemplate\Model\Uitemplate'       => __DIR__ . '/src/Uitemplate/Model/Uitemplate.php',
  'Uitemplate\Model\UitemplateMapper' => __DIR__ . '/src/Uitemplate/Model/UitemplateMapper.php',
);
