<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption"><i class="icon-reorder"></i>Thêm mới</div>
                </div>

                <div class="portlet-body form">
                    <form method="post" class="form-horizontal" enctype="multipart/form-data">
                        <?php
                            $form = $this->form;
                        ?>
                        <div class="control-group">
                            <label class="control-label">Kiểu</label>
                            <div class="controls">
                                <?=$this->formelement($form->get('type')->setAttributes(['class' => 'm-wrap span5']))?>
                                <?= $this->formelementerrors($form->get('type'),['class' => 'help-block'])?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Tên</label>
                            <div class="controls">
                                <?=$this->formelement($form->get('name')->setAttributes(['class' => 'm-wrap span5']))?>
                                <?= $this->formelementerrors($form->get('name'),['class' => 'help-block'])?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Mã màu</label>
                            <div class="controls">
                                <?=$this->formelement($form->get('colorCode')->setAttributes(['class' => 'm-wrap span5 colorpicker-default']))?>
                                <?= $this->formelementerrors($form->get('colorCode'),['class' => 'help-block'])?>
                            </div>
                        </div>
                        <div class="form-actions">
                            <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn blue']))?>
                            <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>