<?php
echo $this->headtitle($this->escapehtml($this->translate('Thêm')));
?>
<script>
//    $(function(){
//        $('#textarea_full').summernote({
//            height: 250
//        });
//    });
</script>
<div class="container-fluid">
<div class="row-fluid">
    <div class="span12">
    </div>
</div>
<form method="post" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="span8" style="">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-navicon"></i>Thêm danh mục</div>
                </div>
                <div class="portlet-body form">
                    <?php
                        $form = $this->form;
                    ?>
                    <div class="row-fluid">
                        <div class="span9">
                            <div class="control-group">
                                <label class="control-label" for="firstName">Tên danh mục</label>
                                <div class="controls">
                                    <?=$this->formelement($form->get('name')->setAttributes(['class' => 'm-wrap span12','placeholder'=>'Tên danh mục']))?>
                                    <?= $this->formelementerrors($form->get('name'),['class' => 'help-block'])?>
                                </div>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="control-group">
                                <label class="control-label" for="firstName">Danh mục cha</label>
                                <div class="controls">
                                    <?=$this->formelement($form->get('parentId')->setAttributes(['class' => 'm-wrap span12','placeholder'=>'Danh mục cha']))?>
                                    <?= $this->formelementerrors($form->get('parentId'),['class' => 'help-block'])?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group">
                                <label class="control-label" for="firstName">Mô tả</label>
                                <div class="controls">
                                    <?=$this->formelement($form->get('description')->setAttributes(['class' => 'm-wrap span12','placeholder'=>'Mô tả']))?>
                                    <?= $this->formelementerrors($form->get('description'),['class' => 'help-block'])?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <?=$this->formelement($form->get('submit')->setAttributes(['class' => 'btn blue']))?>
                        <?=$this->formelement($form->get('reset')->setAttributes(['class' => 'btn']))?>
                    </div>

                </div>
            </div>
        </div>

        <div class="span4">
            <div class="portlet box grey">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-navicon"></i>Tùy chọn</div>
                </div>
                <div class="portlet-body">
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <label class="control-label" for="firstName">Trạng thái</label>
                                <div class="controls">
                                    <?=$this->formelement($form->get('status')->setAttributes(['class' => 'm-wrap span12','tabindex' => '1']))?>
                                    <?= $this->formelementerrors($form->get('status'),['class' => 'help-block'])?>
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group">
                                <label class="control-label" for="firstName">Doanh nghiệp</label>
                                <div class="controls">
                                    <?=$this->formelement($form->get('storeId')->setAttributes(['class' => 'm-wrap span12','tabindex' => '1']))?>
                                    <?= $this->formelementerrors($form->get('storeId'),['class' => 'help-block'])?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">

                    </div>
                </div>
            </div>
        </div>
        <div class="span4">
            <div class="portlet box grey">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-navicon"></i>Hình ảnh</div>
                </div>
                <div class="portlet-body">
                    <div class="control-group">
                        <!-- Button to trigger modal -->
                        <a id="abc" href="#TaskListDialog" role="button" class="btn btn-block" data-toggle="modal">Hình ảnh <i class="fa fa-upload"></i></a>
                        <ul id="imagesLibrary" class="listImage1">

                            <div class="clear"></div>
                        </ul>
                        <?=$this->formelement($form->get('images')->setAttributes(['class' => 'm-wrap span12','id' => 'images']))?>
                        <div id="TaskListDialog" class="modal hide in" tabindex="-1" role="dialog" aria-labelledby="windowTitleLabel">
                            <div class="modal-header">
                                <h3>Hình ảnh</h3>
                            </div>
                            <div class="modal-body">
                                <div class="tabbable">
                                    <ul class="nav nav-tabs">
                                        <li class="active"><a href="#tab1" data-toggle="tab">Danh sách</a></li>
                                        <li><a href="#tab2" data-toggle="tab">Upload</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="tab1">
                                            <div id="dataImage" class="" style="overflow-y: scroll;height: 300px">
                                                <ul id="listImage" class="listImage">

                                                </ul>
                                            </div>
                                        </div>
                                        <div class="tab-pane" id="tab2">
                                            <label id="percentComplete">Lưu ý ảnh nhỏ hơn 3Mb</label>
                                            <input type="file" name="imagemulti[]" class="m-wrap btn-block" id="imagemulti" multiple="multiple">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a id="insertMulti" class="btn btn-primary">Sử dụng</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>
</form>
</div>
<style>
    .portlet-tabs .nav-tabs{
        height: 41px;
    }
    .nav-tabs li a{
        /*color: #FFF;*/
    }
    .nav-tabs li a:hover{
        color: #333;
    }
    #image_upload, #imagemulti, #imagemulti1{
        border: none;
        overflow: hidden;
    }
    #image_upload:focus, #imagemulti:focus, #imagemulti1:focus{
        outline: none;
    }
    #image_upload:before, #imagemulti:before, #imagemulti1:before{
        content: 'Chọn File ảnh';
        display: inline-block;
        background: #FFF;
        border: 1px solid #CCC;
        padding: 1px 0;
        width: 99%;
        outline: none;
        white-space: nowrap;
        -webkit-user-select: none;
        cursor: pointer;
        text-shadow: 1px 1px #fff;
        font-size: 10pt;
        text-indent: 10px;
    }
    #imagemulti1:before{
        border: none;
    }
    ul.listImage1{
        margin: 10px 0 5px 0;
        padding: 0 0;
    }
    ul.listImage1 li{
        list-style: none;
        width: 24%;
        margin: 0 1% 2px 0;
        display: inline-block;
        position: relative;
        height: 50px;
        overflow: hidden;
        background: #ccc;
    }
    ul.listImage1 li.active:before{
        content: 'Sử dụng';
        width: 100%;
        height: 100%;
        display: block;
        background: rgba(60, 60, 60, 0.52);
        opacity: 1;
        top: 0;
        line-height: 80px;
        color: #FFF;
        left: 0;
        z-index: 1;
        position: absolute;
        text-align: center;
    }
    ul.listImage1 li img{
        max-width: 100%;
        position: absolute;
        top: 0;
        bottom: 0;
        margin: auto;
    }
    .clear{clear: both}
</style>
<?php
//    echo $this->headScript()->prependFile($this->basePath() . '/js/admin/article/a.js', 'text/javascript');
?>