<?php
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h3 class="page-title">
                Danh sách thuộc tính
            </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/admin">Admin</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="/admin/product/attr">Thuộc tính</a>
                </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-edit"></i>Danh sách thuộc tính</div>
                </div>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a href="/admin/product/addattr" id="sample_editable_1_new" class="btn green">
                                Thêm mới <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Công cụ <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Print</a></li>
                                <li><a href="#">Save as PDF</a></li>
                                <li><a href="#">Export to Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row-fluid">
                            <div class="span6"></div>
                        </div>
                        <div class="dg-container">
                            <?php
                                $dg = new Admin\Dg\DgAttr(['dataSource' => $this->results]);
                                echo $this->partial('partial/dataGrid', [
                                    'dataGrid' => $dg,
                                ]);
                            ?>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
<style>
    .dg-container{
        display: inline-block;
        width: 100%;
    }
</style>