<?php
//echo $this->headScript()->prependFile($this->basePath() . '/js/product/product.js', 'text/javascript');
echo $this->headtitle($this->escapehtml($this->translate('Danh sách sản phẩm')));

?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h3 class="page-title">
                Danh mục sản phẩm
            </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/admin">Admin</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="/admin/product/category">Danh mục</a>
                </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-edit"></i>Danh mục sản phẩm</div>
                </div>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a href="/admin/product/addcategory" id="sample_editable_1_new" class="btn green">
                                Thêm mới <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Công cụ <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Print</a></li>
                                <li><a href="#">Save as PDF</a></li>
                                <li><a href="#">Export to Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row-fluid">
                            <div class="span2"></div>
                            <div class="span10">
                                <?php
                                echo $this->partial ( 'partial/form', array (
                                    'form' => $this->fFilter
                                ));

                                ?>
                            </div>
                        </div>
                        <?php
                        echo $dg = new \Admin\Dg\DgProductc ( array (
                            'data' => $this->results->getData (),
                            'paging' => $this->results->getPaging (),
                            'rowCount' => $this->results->getRowCount (),
                            'rowInPage' => $this->results->getRowInPage (),
                        ));
                        ?>
                    </div>

                </div>

            </div>
        </div>
    </div>

</div>

<div id="confdelete"></div>
<div id="err"></div>
<div id="uploadimg"></div>
<style>
    .dg-container{
        display: inline-block;
        width: 100%;
    }
    .fFilter{
        text-align: right;
    }
    .fFilter #id{
        width: 10% !important;
        margin: 0 5px 0 0;
    }
    .fFilter #name{
        margin: 0 5px 0 0;
    }
</style>
<script>
    $(function(){
        $('.changeType').click(function(){
            var id = $(this).attr('data-id'), _this = $(this);
            $.post('/admin/product/changec',{id: id},function(r){
                if(r.code == 1){
                    if(r.status == 1){
                        _this.find('i').remove();
                        _this.append('<i class="fa fa-eye"></i>');
                    }else if(r.status == 0){
                        _this.find('i').remove();
                        _this.append('<i class="fa fa-eye-slash"></i>');
                    }
                }else if(r.code == 0){
                    alert(r.messenger);
                }
            });
        });

        $('.updateOrder').click(function(){
            var id = $(this).attr('data-id'), _this = $(this);
            $.post('/admin/product/changec',{id: id, order: true},function(r){
                if(r.code == 1){
                    location.reload();
                }else if(r.code == 0){
                    alert(r.messenger);
                }
            });
        });

        var hide = true;
        var t = $('.deleteCategory');
        var clicks = true;

        t.click(function() {
            var t = $(this);
            var td = t.closest('tr');
            if (clicks) {
                $(this).text('OK');
                $(this).removeClass('fa fa-trash-o');
                clicks = false;
            } else {
                $.post('/admin/product/deletecategory',{
                    id: $(this).attr('data-id'),
                },function(r){
                    if(r.code == 0){
                        alert('We are can not find product on system');
                    }else if(r.code == 1){
                        td.fadeOut(600,function(){
                            td.remove();
                        });
                    }
                });
                clicks = true;
            }
        });

        $('html').click(function(e){
            if ($(e.target).hasClass('deleteCategory')) {
                return false;
            }
            if(hide){
                t.addClass('fa fa-trash-o').text('');
            }
            clicks = true;
            hide = true;
        });



    });
</script>