<?php
echo $this->headtitle($this->escapehtml($this->translate('Danh sách đơn hàng')));
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h3 class="page-title">
                Danh sách đơn hàng
            </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/admin">Admin</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="/admin/product/order">đơn hàng</a>
                </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption"><i class="fa fa-edit"></i>Danh sách đơn hàng</div>
                </div>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a style="cursor: no-drop" id="sample_editable_1_new" class="btn green">
                                Thêm mới <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Công cụ <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Print</a></li>
                                <li><a href="#">Save as PDF</a></li>
                                <li><a href="#">Export to Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row-fluid">
                            <div class="span2"></div>
                            <div class="span10">
                                <?php
                                echo $this->partial ( 'partial/form', array (
                                    'form' => $this->fFilter
                                ));
                                ?>
                            </div>
                        </div>
                        <?php
                        echo $dg = new \Admin\Dg\DgOrder ( array (
                            'data' => $this->results->getData (),
                            'paging' => $this->results->getPaging (),
                            'rowCount' => $this->results->getRowCount (),
                            'rowInPage' => $this->results->getRowInPage (),
                        ));
                        ?>
                    </div>

                </div>

            </div>
        </div>
    </div>

</div>

<div id="confdelete"></div>
<div id="err"></div>
<div id="uploadimg"></div>
<style>
    .dg-container{
        display: inline-block;
        width: 100%;
    }
    .fFilter{
        text-align: right;
    }
    .fFilter #id{
        width: 10% !important;
        margin: 0 5px 0 0;
    }
    .fFilter #name{
        margin: 0 5px 0 0;
    }
</style>