<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Home\Module'                        => __DIR__ . '/Module.php',
  'Home\Controller\IndexController'    => __DIR__ . '/src/Home/Controller/IndexController.php',
  'Home\Controller\LoadviewController' => __DIR__ . '/src/Home/Controller/LoadviewController.php',
  'Home\Controller\SearchController'   => __DIR__ . '/src/Home/Controller/SearchController.php',
  'Home\Controller\ContactController'  => __DIR__ . '/src/Home/Controller/ContactController.php',
  'Home\Model\DateBase'                => __DIR__ . '/src/Home/Model/DateBase.php',
  'Home\Model\Base'                    => __DIR__ . '/src/Home/Model/Base.php',
  'Home\Model\BaseMapper'              => __DIR__ . '/src/Home/Model/BaseMapper.php',
  'Home\View\Helper\Media'             => __DIR__ . '/src/Home/View/Helper/Media.php',
  'Home\View\Helper\MediaFactory'      => __DIR__ . '/src/Home/View/Helper/MediaFactory.php',

);
