<?php
//$c = $this->category;
//$this->headTitle($this->escapeHtml($this->translate($c->getName())));
//$this->headMeta()->appendName('description', ($c->getDescription() ? : $c->getDescription()));
//$this->headMeta()->appendName('keywords', ($c->getName() ? : $c->getName()));
//$this->headMeta()->appendProperty('og:title', $c->getName());
?>
<div class="wrapper">
    <div class="header">
        <div class="container">
            <div class="col-md-12">
                <div class="logo">
                    <a href="/" title="Differrence Web"><img src="/tp/dweb/image/dweb.png" alt="Differrence Web" /></a>
                </div>
            </div>
        </div>
    </div>