<?php
    $this->headTitle($this->escapeHtml($this->translate('Trang chủ')));
    $this->headMeta()->appendName('description', ('Trang chủ'));
    $this->headMeta()->appendName('keywords', ('Trang chủ'));
    $this->headMeta()->appendProperty('og:title', 'Trang chủ');
?>

<div class="main">
    <div class="container">
        <div class="row">
            <h2>Home</h2>
        </div>
    </div>
</div>